In [1]:
import pandas as pd
data = pd.read_parquet("train.parquet")

data.head()

,text,label,file_name,file_path,parent_folder,chunk_text,chunk_index,embedding_model,emb_0,emb_1,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
0,This is a digital copy of a book that ...,0,reliquiantiqusc00phigoog_djvu.txt,data/raw/non_cooking/archive-americana-fiction...,archive-americana-fiction-literature-technolog...,This is a digital copy of a book that ...,0,unknown_model,-0.041824,-0.018007,...,-0.030495,-0.013572,-0.016870,0.051851,-0.070934,-0.020697,0.067925,-0.058811,-0.011301,0.027905
1,This is a digital copy of a book that ...,0,reliquiantiqusc00phigoog_djvu.txt,data/raw/non_cooking/archive-americana-fiction...,archive-americana-fiction-literature-technolog...,t term has expired. Whether a book is ...,1,unknown_model,-0.046516,-0.021801,...,-0.001311,-0.006935,0.051186,0.036030,-0.047180,-0.029535,0.088211,-0.101848,-0.044295,0.005107
2,This is a digital copy of a book that ...,0,reliquiantiqusc00phigoog_djvu.txt,data/raw/non_cooking/archive-americana-fiction...,archive-americana-fiction-literature-technolog...,to a library and finally to you. \n\nUsa...,2,unknown_model,-0.075880,-0.002500,...,0.025578,-0.052126,0.022998,0.008374,-0.012486,0.053609,0.063775,0.032146,-0.008220,0.036337
3,This is a digital copy of a book that ...,0,reliquiantiqusc00phigoog_djvu.txt,data/raw/non_cooking/archive-americana-fiction...,archive-americana-fiction-literature-technolog...,ding placing technical restrictions on au...,3,unknown_model,-0.073942,-0.011211,...,0.008760,0.006203,0.043453,0.014544,0.042812,-0.001370,0.036819,-0.003558,-0.040057,-0.004867
4,This is a digital copy of a book that ...,0,reliquiantiqusc00phigoog_djvu.txt,data/raw/non_cooking/archive-americana-fiction...,archive-americana-fiction-literature-technolog...,"achine \ntranslation, optical character rec...",4,unknown_model,-0.104148,-0.050326,...,-0.031083,-0.007277,0.026655,0.003161,0.047510,0.009597,0.082639,-0.005786,-0.048058,-0.006862

In [2]:
data.describe()

,label,chunk_index,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
count,6702.0,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,...,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000,6702.000000
mean,0.0,1702.717249,-0.039936,0.033688,0.008185,-0.010321,-0.034964,0.000883,0.052213,0.035194,...,-0.014741,-0.009407,-0.005614,0.007264,-0.016826,-0.006562,0.029083,0.031899,0.016415,-0.019080
std,0.0,1013.919283,0.044402,0.045661,0.052563,0.046300,0.045930,0.041360,0.056222,0.047332,...,0.042487,0.045996,0.041915,0.047451,0.046348,0.038642,0.049394,0.044062,0.047576,0.044126
min,0.0,0.000000,-0.197763,-0.145529,-0.184434,-0.147660,-0.210598,-0.160204,-0.157062,-0.149919,...,-0.170954,-0.181035,-0.178828,-0.175076,-0.205529,-0.143988,-0.152633,-0.140639,-0.158408,-0.187555
25%,0.0,837.250000,-0.069375,0.003764,-0.028695,-0.043473,-0.066774,-0.026600,0.012606,0.003189,...,-0.043452,-0.040474,-0.033194,-0.024535,-0.047946,-0.032701,-0.003739,0.003051,-0.015628,-0.049101
50%,0.0,1675.000000,-0.040099,0.035755,0.008531,-0.012478,-0.035503,0.001811,0.053027,0.034087,...,-0.014795,-0.009625,-0.005256,0.009420,-0.017128,-0.006830,0.029897,0.031896,0.017387,-0.020160
75%,0.0,2512.750000,-0.011183,0.065002,0.045824,0.019167,-0.004575,0.028946,0.091903,0.066722,...,0.015041,0.021815,0.022704,0.040305,0.014120,0.019254,0.062941,0.061188,0.050162,0.010605
max,0.0,3781.000000,0.122865,0.183878,0.185572,0.157302,0.137925,0.150090,0.229153,0.207376,...,0.178531,0.159062,0.153640,0.192312,0.163082,0.131272,0.199594,0.186746,0.192652,0.143951